import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import Menu from "@/components/Menu";
import AltBilgi from "@/components/AltBilgi";
import DuyuruCubugu from "@/components/DuyuruCubugu";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="tr"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <DuyuruCubugu />
        <header className="bg-blue-800 text-white">
          <div className="max-w-5xl mx-auto px-4 py-4 flex flex-col sm:flex-row items-center justify-between gap-2">
            <Link href="/" className="text-xl font-bold">
              📚 Okul Kütüphanesi
            </Link>
            <Menu />
          </div>
        </header>
        <div className="flex-1 w-full max-w-5xl mx-auto px-4 py-8">{children}</div>
        <AltBilgi />
      </body>
    </html>
  );
}
